= Compatibility

[abstract]
Compatibility information for kafka-connect-couchbase version 4.x.

.Legend
* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.

* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade to a supported version.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

Support for specific versions of Apache Kafka and Confluent Platform is informed by https://docs.confluent.io/platform/current/installation/versions-interoperability.html[Confluent Platform Supported Versions and Interoperability].

== Apache Kafka
[%autowidth,cols="^,2*^"]
|===
 |                   2+h| Connector
h| Apache Kafka ↓ | 4.0 | 4.1
 | 2.4 or later   | ✔   | ✔
 | 1.1 - 2.3      | ✔   | ✖
|===

== Confluent Platform (Optional)
[%autowidth,cols="^,2*^"]
|===
 |                   2+h| Connector
h| Confluent Platform ↓ | 4.0 | 4.1
 | 5.4 or later         | ✔   | ✔
 | 4.1 - 5.3            | ✔   | ✖
|===

== Couchbase Server

The connector is compatible with Couchbase Server Enterprise Edition and Couchbase Server Community Edition.

[%autowidth,cols="^,3*^"]
|===
 |           3+h| Connector
h| Couchbase↓    | 4.0.x | 4.1.0 | 4.1.1+
 | 7.0.2+        | ✖     | ✖     | ✔
 | 7.0.0 - 7.0.1 | ◎ *   | ✔     | ✔
 | 6.x           | ✔     | ✔     | ✔
 | 5.x           | ✔     | ◎     | ◎
 | < 5.0         | ✖     | ✖     | ✖
|===
+++*+++ If you've been using an earlier version of Couchbase, you can upgrade to Couchbase 7 and everything will continue working as before.
To take advantage of the Scopes and Collections introduced in Couchbase 7, please upgrade the connector to version 4.1.

== Couchbase Capella

Connector versions 4.0.1 and later are compatible with Couchbase Capella.
