= Introduction

[abstract]
The Couchbase Kafka connector is a plug-in for the https://kafka.apache.org/documentation.html#connect[Kafka Connect] framework.
It provides source and sink components.

The source connector streams documents from Couchbase Server using the high-performance Database Change Protocol (DCP) and publishes the latest version of each document to a Kafka topic in near real-time.

The sink connector subscribes to Kafka topics and writes the messages to Couchbase Server.

[[delivery-guarantees]]
== Source Connector Delivery Guarantees

The source connector guarantees "at least one" delivery of _the latest version_ of each document.

In some situations the source connector may "rewind" the document stream and restart from an earlier point in history.

Except for rewinding, the source connector preserves the order of changes within the same Couchbase partition (or "virtual bucket"), and changes to a document are published in the order they occurred.

The order between changes in different Couchbase partitions is *not* guaranteed.

When a document is removed from Couchbase due to expiration, the connector does not publish the deletion until the expired document is xref:server:learn:data/expiration.adoc#post-expiration-purging[purged from Couchbase].

WARNING: The source connector *does not* guarantee every version of a document will be reflected in the Kafka topic.
For example, if a Couchbase document value changes rapidly from `V1` -> `V2` -> `V3`, or if the connector is not running when the change occurs, the connector is only guaranteed to publish the latest value (`V3`).

For use cases that require every document version be reflected in the event stream without fail, two popular options are:

1. Treat the documents as immutable, and write a new document for each application event.
In other words, make `V1`, `V2`, and `V3` separate documents.

2. Include a version history inside each document.
For example, the first version of a document would be just `[V1]`.
The second version would add `V2`, resulting in `[V1,V2]`.
After adding `V3`, it would be `[V1,V2,V3]`.

== Compatibility

Refer to the xref:compatibility.adoc[] page for information on compatible versions of Kafka and Couchbase Server.

== Contributing

Couchbase welcomes community contributions to the Kafka connector.
The https://github.com/couchbase/kafka-connect-couchbase[Kafka Connector source code^] is available on GitHub.
