= Release Notes

[abstract]
Release notes, installation instructions, and download archive for the Couchbase Kafka Connector.

This page covers version 4.0.x of the Couchbase Kafka Connector.
For earlier versions, please see the xref:3.4@release-notes.adoc[3.x Release Notes].

== Installation

Scroll down to the version you want, then click the "Download" link to get the full connector distribution.
Refer to the xref:quickstart.adoc[Quickstart Guide] for detailed installation instructions.

=== Java API Maven Coordinates
You can optionally extend the connector's functionality by writing custom components.
Include the connector's Java API in your custom component Maven project by adding this dependency to your POM:

[source,xml]
----
<dependency>
    <groupId>com.couchbase.client</groupId>
    <artifactId>kafka-connect-couchbase</artifactId>
    <version><!-- connector version --></version>
</dependency>
----


[[v4.0.0-dp.1]]
== Version 4.0.0-dp.1 (17 June 2020)

https://packages.couchbase.com/clients/kafka/4.0.0-dp.1/couchbaseinc-kafka-connect-couchbase-4.0.0-dp.1.zip[Download]

This developer preview version offers a sneak peek at some features coming in version 4.0.0 of the Couchbase Kafka connector, including support for Couchbase Collections and Scopes.

Version 4.0 is a major update that changes how you configure and extend the connector.
If you are upgrading from a previous version of the connector, be sure to read the xref:migration.adoc[Migration Guide] which will help you with the upgrade process.

NOTE: The new features in this pre-release version should be considered "volatile" and may change before the 4.0.0 GA release.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-182[KAFKAC-182]:
Upgraded Kafka Connect API from 1.0.2 to 2.5.0.

* https://issues.couchbase.com/browse/KAFKAC-188[KAFKAC-188]:
Upgraded Couchbase client from 2.7.13 to 3.0.5.

* https://issues.couchbase.com/browse/KAFKAC-189[KAFKAC-189]:
Upgraded DCP client from 0.26.0 to 0.28.0.

* https://issues.couchbase.com/browse/KAFKAC-192[KAFKAC-192]:
Renamed the connector config properties to follow the standard Kafka naming convention ("lowercase.with.dots.between.words").
See the xref:migration.adoc[Migration Guide] for a comprehensive list of changes, and a shell script that can help upgrade your 3.x config files to use the new property names.

* https://issues.couchbase.com/browse/KAFKAC-196[KAFKAC-196]:
Source: Added `couchbase.scope` and `couchbase.collection` config properties that let you stream from a specific scope or set of collections.

* https://issues.couchbase.com/browse/KAFKAC-195[KAFKAC-195]:
Source: Modified the `couchbase.topic` config property to be a format string that supports `${bucket}`, `${scope}`, and `${collection}` placeholders.
This makes it easy to publish to different Kafka topics depending on the Couchbase document's parent collection.
The default value is `${bucket}.${scope}.${collection}`.

* https://issues.couchbase.com/browse/KAFKAC-194[KAFKAC-194]:
Source: A custom `SourceHandler` can now set headers on the Kafka record.

* https://issues.couchbase.com/browse/KAFKAC-157[KAFKAC-157]:
The connector is now packaged as a Confluent Hub component.
Confluent Platform users can easily install the connector using the `confluent-hub install` command.
The xref:quickstart.adoc[Quickstart Guide] has been updated to show how Apache Kafka users can install the connector.

* https://issues.couchbase.com/browse/KAFKAC-167[KAFKAC-167]:
You can now specify custom ports in the list of Couchbase seed nodes.
If you specify a port, it must be the port of the Key/Value service (which defaults to 11210 for unencrypted connections).

* https://issues.couchbase.com/browse/KAFKAC-171[KAFKAC-171]:
The `couchbase.password` config property (previously called `connection.password`) no longer defaults to an empty string.

* https://issues.couchbase.com/browse/KAFKAC-173[KAFKAC-173]:
The `couchbase.connector.name.in.offsets` config property (previously called `compat.connector_name_in_offsets`) now defaults to `true`.

* https://issues.couchbase.com/browse/KAFKAC-175[KAFKAC-175]:
APIs deprecated in version 3.x have been removed.

*Parent topic:* xref:index.adoc[Kafka Connector]

*Previous topic:* xref:streams-sample.adoc[Couchbase Sample with Kafka Streams]
