= Release Notes

[abstract]
Release notes, installation instructions, and download archive for the Couchbase Kafka Connector.

This page covers version 4.0.x of the Couchbase Kafka Connector.
For earlier versions, please see the xref:3.4@release-notes.adoc[3.x Release Notes].

== Installation

Scroll down to the version you want, then click the "Download" link to get the full connector distribution.
Refer to the xref:quickstart.adoc[Quickstart Guide] for detailed installation instructions.

=== Java API Maven Coordinates
You can optionally extend the connector's functionality by writing custom components.
When developing a custom component, include the connector's Java API in your Maven project by adding this dependency to your POM:

[source,xml]
----
<dependency>
    <groupId>com.couchbase.client</groupId>
    <artifactId>kafka-connect-couchbase</artifactId>
    <version><!-- connector version --></version>
</dependency>
----

[[v4.0.2]]
== Version 4.0.2 (17 November 2020)

https://packages.couchbase.com/clients/kafka/4.0.2/couchbase-kafka-connect-couchbase-4.0.2.zip[Download]

In this release, the connector publishes metrics via JMX to facilitate monitoring.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-152[KAFKAC-152]:
*Documentation* - Added a "Monitoring" page which refers users to the Kafka Connect framework documentation for monitoring connectors via JMX.

* https://issues.couchbase.com/browse/KAFKAC-232[KAFKAC-232]:
*Source* - Metrics specific to the Couchbase source connector are now exposed via JMX under the `kafka.connect.couchbase` domain.

* https://issues.couchbase.com/browse/KAFKAC-110[KAFKAC-110]:
*Source* - Added a gauge that reports the Couchbase connection status.

* https://issues.couchbase.com/browse/KAFKAC-231[KAFKAC-231]:
*Source* - Upgrade DCP client from 0.30.0 to 0.31.0

[[v4.0.1]]
== Version 4.0.1 (20 October 2020)

https://packages.couchbase.com/clients/kafka/4.0.1/couchbase-kafka-connect-couchbase-4.0.1.zip[Download]

This release improves compatibility with Couchbase Cloud, and exposes extended attributes (XATTRS) to custom components.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-227[KAFKAC-227]:
*Source* - Added config property `couchbase.xattrs` (boolean, defaults to false).
If set to true, a custom `Filter` or `SourceHandler` may inspect a document's extended attributes by calling `DocumentEvent.xattrs()`.

* https://issues.couchbase.com/browse/KAFKAC-226[KAFKAC-226]:
Renamed the ZIP archive from `couchbaseinc-kafka-connect-couchbase` to `couchbase-kafka-connect-couchbase` (removed the "inc" from "couchbaseinc").
This made it easier to publish the connector on https://www.confluent.io/hub/couchbase/kafka-connect-couchbase[Confluent Hub].

* https://issues.couchbase.com/browse/KAFKAC-228[KAFKAC-228]:
Upgraded the Couchbase Java SDK from 3.0.6 to 3.0.9.
Bootstrap performance is improved when specifying custom ports, and the connector no longer logs spurious warnings about being unable to fetch collections manifests.

* https://issues.couchbase.com/browse/KAFKAC-229[KAFKAC-229]:
Upgraded the DCP client from 0.29.0 to 0.30.0, adding support for XATTRs.

=== Bug Fixes

* https://issues.couchbase.com/browse/KAFKAC-225[KAFKAC-225]:
Fixed a regression in version 4.0.0 that broke alternate address resolution.
The connector now handles DNS SRV and alternate addresses correctly, and can connect to Couchbase Cloud or other network environments that use alternate addresses.

[[v4.0.0]]
== Version 4.0.0 (18 August 2020)

https://packages.couchbase.com/clients/kafka/4.0.0/couchbaseinc-kafka-connect-couchbase-4.0.0.zip[Download]

Version 4.0 is a major update that changes how you configure and extend the connector.
If you are upgrading from a previous version of the connector, be sure to read the xref:migration.adoc[Migration Guide] which will help with the upgrade process.

The leap to 4.0 brings many new features, most notably:

* Enhanced durability options (requires Couchbase 6.5)
* Better workload distribution
* More flexible API for extensions
* Option to omit document contents
* Support for Couchbase collections and scopes (planned for Couchbase 7.0)

The notes below describe these features, and more.

WARNING: The new configuration properties related to Couchbase scopes and collections are "uncommitted" and may change without notice in a patch release.

=== Enhancements
[abstract]
Complete list of changes since version 3.4.8

* https://issues.couchbase.com/browse/KAFKAC-192[KAFKAC-192]:
Renamed the connector config properties to follow the standard Kafka naming convention ("lowercase.with.dots.between.words").
See the xref:migration.adoc[Migration Guide] for a comprehensive list of changes, and a shell script that can help upgrade your 3.x config files to use the new property names.

* https://issues.couchbase.com/browse/KAFKAC-157[KAFKAC-157]:
The connector is now packaged as a Confluent Hub component.
Confluent Platform users can easily install the connector using the `confluent-hub install` command.
The xref:quickstart.adoc[Quickstart Guide] has been updated to show how Apache Kafka users can install the connector.

* https://issues.couchbase.com/browse/KAFKAC-167[KAFKAC-167]:
You can now specify custom ports in the list of Couchbase seed nodes.
If you specify a port, it must be the port of the Key/Value service (which defaults to 11210 for unencrypted connections).

* https://issues.couchbase.com/browse/KAFKAC-207[KAFKAC-207]:
*Sink* - You can now specify an "enhanced durability" requirement with the new `couchbase.durability` config property.
Enhanced durability requires Couchbase Server 6.5 or later.

* https://issues.couchbase.com/browse/KAFKAC-197[KAFKAC-197]:
*Sink* - Added config property `couchbase.topic.to.collection` which maps Kafka topics to Couchbase collections.
Added config property `couchbase.default.collection` which is used when a message's topic is not present in the map.

* https://issues.couchbase.com/browse/KAFKAC-209[KAFKAC-209]:
*Source* - The connector now evenly distributes the workload among all tasks, instead of trying to minimize the total number of Couchbase connections.

* https://issues.couchbase.com/browse/KAFKAC-177[KAFKAC-177]:
*Source* - The example config files now use `RawJsonSourceHandler` and publish Kafka messages whose contents are the same as the Couchbase documents.

* https://issues.couchbase.com/browse/KAFKAC-212[KAFKAC-212]:
*Source* - If you don't care about the content of the Couchbase document, you can set the new `couchbase.no.value` config property to `true`, and the connector will omit the document content from Kafka messages.

* https://issues.couchbase.com/browse/KAFKAC-194[KAFKAC-194]:
*Source* - A custom `SourceHandler` can now set headers on the Kafka record.

* https://issues.couchbase.com/browse/KAFKAC-223[KAFKAC-223]:
*Source* - The connector is now more responsive to "pause" requests.

* https://issues.couchbase.com/browse/KAFKAC-220[KAFKAC-220]:
*Source* - Custom `Filter` and `SourceHandler` components can now access connector configuration properties.
These interfaces now have an `init(Map<String, String>)` method.
The connector config is passed to this method when the component is created.

* https://issues.couchbase.com/browse/KAFKAC-222[KAFKAC-222]:
The `custom-extensions` example project now includes a `CustomFilter` class that demonstrates how to read properties from the connector config.
This example filter accepts or rejects documents based on a field of the document.
The target field and the list of acceptable values are both configurable.

* https://issues.couchbase.com/browse/KAFKAC-196[KAFKAC-196]:
*Source* - Added `couchbase.scope` and `couchbase.collection` config properties that let you stream from a specific scope or set of collections.

* https://issues.couchbase.com/browse/KAFKAC-195[KAFKAC-195]:
*Source* - Modified the `couchbase.topic` config property to be a format string that supports `${bucket}`, `${scope}`, and `${collection}` placeholders.
This makes it easy to publish to different Kafka topics depending on the Couchbase document's parent collection.
The default value is `${bucket}.${scope}.${collection}`.

* https://issues.couchbase.com/browse/KAFKAC-171[KAFKAC-171]:
The `couchbase.password` config property (previously called `connection.password`) no longer defaults to an empty string.

* https://issues.couchbase.com/browse/KAFKAC-175[KAFKAC-175]:
APIs deprecated in version 3.x have been removed.

* Upgraded Kafka Connect API from 1.0.2 to 2.5.0.

* Upgraded Couchbase client from 2.7.13 to 3.0.6.

* Upgraded DCP client from 0.26.0 to 0.29.0.

=== Bug Fixes

[abstract]
Complete list of changes since version 3.4.8

* https://issues.couchbase.com/browse/KAFKAC-169[KAFKAC-169]:
*Sink* - If two Kafka messages with the same key arrive in rapid succession, it's no longer theoretically possible for them to be written to Couchbase in the wrong order.

=== Changes since 4.0.0-dp.3

* https://issues.couchbase.com/browse/KAFKAC-220[KAFKAC-220]:
*Source* - Custom `Filter` and `SourceHandler` components can now access connector configuration properties.
These interfaces now have an `init(Map<String, String>)` method.
The connector config is passed to this method when the component is created.

* https://issues.couchbase.com/browse/KAFKAC-222[KAFKAC-222]:
The `custom-extensions` example project now includes a `CustomFilter` class that demonstrates how to read properties from the connector config.
This example filter accepts or rejects documents based on a field of the document.
The target field and the list of acceptable values are both configurable.

[[v4.0.0-dp.3]]
== Version 4.0.0-dp.3 (21 July 2020)

https://packages.couchbase.com/clients/kafka/4.0.0-dp.3/couchbaseinc-kafka-connect-couchbase-4.0.0-dp.3.zip[Download]

In this developer preview, both the Sink and Source connector now support Couchbase collections.
This preview also brings a handful of fixes and new features, including support for enhanced durability, and optionally omitting document contents.

NOTE: The new features in this pre-release version should be considered "volatile" and may change before the 4.0.0 GA release.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-197[KAFKAC-197]:
*Sink* - Added config property `couchbase.topic.to.collection` which maps Kafka topics to Couchbase collections.
Added config property `couchbase.default.collection` which is used when a message's topic is not present in the map.

* https://issues.couchbase.com/browse/KAFKAC-207[KAFKAC-207]:
*Sink* - You can now specify an "enhanced durability" requirement with the new `couchbase.durability` config property.
Enhanced durability requires Couchbase Server 6.5 or later.

* https://issues.couchbase.com/browse/KAFKAC-206[KAFKAC-206]:
*Source* - Config property `couchbase.connector.name.in.offsets` now defaults to false again.
This property doesn't do anything useful, and should only be set to `true` if you previously had `compat.connector_name_in_offsets` set to `true`.

* https://issues.couchbase.com/browse/KAFKAC-177[KAFKAC-177]:
*Source* - The example config files now use `RawJsonSourceHandler` and publish Kafka messages whose contents are the same as the Couchbase documents.

* https://issues.couchbase.com/browse/KAFKAC-209[KAFKAC-209]:
*Source* - The connector now evenly distributes the workload among all tasks, instead of trying to minimize the total number of Couchbase connections.

* https://issues.couchbase.com/browse/KAFKAC-212[KAFKAC-212]:
*Source* - If you don't care about the content of the Couchbase document, you can set the new `couchbase.no.value` config property to `true`, and the connector will omit the document content from Kafka messages.

* https://issues.couchbase.com/browse/KAFKAC-205[KAFKAC-205]:
Removed the unused `couchbase.force.ipv4` config property.

=== Bug Fixes

* https://issues.couchbase.com/browse/KAFKAC-169[KAFKAC-169]:
*Sink* - If two Kafka messages with the same key arrive in rapid succession, it's no longer theoretically possible for them to be written to Couchbase in the wrong order.

* https://issues.couchbase.com/browse/KAFKAC-214[KAFKAC-214]:
*Sink* - The Couchbase Java SDK has been updated from 3.0.5 to 3.0.6.
As a result, setting `couchbase.document.expiration` to longer than 30 days now works correctly instead of causing immediate expiration.
(This was a regression in 4.0.0-dp.1.)

* https://issues.couchbase.com/browse/KAFKAC-203[KAFKAC-203]:
*Source* - The 3.x -> 4.0 migration script now properly converts the old `couchbase.flow_control_buffer` property to the new name: `couchbase.flow.control.buffer.size`.

* https://issues.couchbase.com/browse/KAFKAC-204[KAFKAC-204]:
*Source* - Fixed the invalid value for `couchbase.bootstrap.timeout` in the `quickstart-couchbase-source.json` example config file.

[[v4.0.0-dp.1]]
== Version 4.0.0-dp.1 (17 June 2020)

https://packages.couchbase.com/clients/kafka/4.0.0-dp.1/couchbaseinc-kafka-connect-couchbase-4.0.0-dp.1.zip[Download]

This developer preview version offers a sneak peek at some features coming in version 4.0.0 of the Couchbase Kafka connector, including support for Couchbase Collections and Scopes.

Version 4.0 is a major update that changes how you configure and extend the connector.
If you are upgrading from a previous version of the connector, be sure to read the xref:migration.adoc[Migration Guide] which will help you with the upgrade process.

NOTE: The new features in this pre-release version should be considered "volatile" and may change before the 4.0.0 GA release.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-182[KAFKAC-182]:
Upgraded Kafka Connect API from 1.0.2 to 2.5.0.

* https://issues.couchbase.com/browse/KAFKAC-188[KAFKAC-188]:
Upgraded Couchbase client from 2.7.13 to 3.0.5.

* https://issues.couchbase.com/browse/KAFKAC-189[KAFKAC-189]:
Upgraded DCP client from 0.26.0 to 0.28.0.

* https://issues.couchbase.com/browse/KAFKAC-192[KAFKAC-192]:
Renamed the connector config properties to follow the standard Kafka naming convention ("lowercase.with.dots.between.words").
See the xref:migration.adoc[Migration Guide] for a comprehensive list of changes, and a shell script that can help upgrade your 3.x config files to use the new property names.

* https://issues.couchbase.com/browse/KAFKAC-196[KAFKAC-196]:
Source: Added `couchbase.scope` and `couchbase.collection` config properties that let you stream from a specific scope or set of collections.

* https://issues.couchbase.com/browse/KAFKAC-195[KAFKAC-195]:
Source: Modified the `couchbase.topic` config property to be a format string that supports `${bucket}`, `${scope}`, and `${collection}` placeholders.
This makes it easy to publish to different Kafka topics depending on the Couchbase document's parent collection.
The default value is `${bucket}.${scope}.${collection}`.

* https://issues.couchbase.com/browse/KAFKAC-194[KAFKAC-194]:
Source: A custom `SourceHandler` can now set headers on the Kafka record.

* https://issues.couchbase.com/browse/KAFKAC-157[KAFKAC-157]:
The connector is now packaged as a Confluent Hub component.
Confluent Platform users can easily install the connector using the `confluent-hub install` command.
The xref:quickstart.adoc[Quickstart Guide] has been updated to show how Apache Kafka users can install the connector.

* https://issues.couchbase.com/browse/KAFKAC-167[KAFKAC-167]:
You can now specify custom ports in the list of Couchbase seed nodes.
If you specify a port, it must be the port of the Key/Value service (which defaults to 11210 for unencrypted connections).

* https://issues.couchbase.com/browse/KAFKAC-171[KAFKAC-171]:
The `couchbase.password` config property (previously called `connection.password`) no longer defaults to an empty string.

* https://issues.couchbase.com/browse/KAFKAC-173[KAFKAC-173]:
The `couchbase.connector.name.in.offsets` config property (previously called `compat.connector_name_in_offsets`) now defaults to `true`.

* https://issues.couchbase.com/browse/KAFKAC-175[KAFKAC-175]:
APIs deprecated in version 3.x have been removed.



== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].

*Parent topic:* xref:index.adoc[Kafka Connector]

*Previous topic:* xref:streams-sample.adoc[Couchbase Sample with Kafka Streams]
