= Release Notes

[abstract]
Release notes, installation instructions, and download archive for the Couchbase Kafka Connector.

This page covers version 4.x of the Couchbase Kafka Connector.
For earlier versions, please see the xref:3.4@release-notes.adoc[3.x Release Notes].

== Installation

Scroll down to the version you want, then click the "Download" link to get the full connector distribution.
Refer to the xref:quickstart.adoc[Quickstart Guide] for detailed installation instructions.

=== Java API Maven Coordinates
You can optionally extend the connector's functionality by writing custom components.
When developing a custom component, include the connector's Java API in your Maven project by adding this dependency to your POM:

[source,xml]
----
<dependency>
    <groupId>com.couchbase.client</groupId>
    <artifactId>kafka-connect-couchbase</artifactId>
    <version><!-- connector version --></version>
</dependency>
----

[[v4.1.11]]
== Version 4.1.11 (17 February 2023)

https://packages.couchbase.com/clients/kafka/4.1.11/couchbase-kafka-connect-couchbase-4.1.11.zip[Download]

The source connector now takes advantage of the new history preservation feature in Couchbase Server 7.2.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-311[KAFKAC-311]:
*Source* If the source bucket is configured to preserve history, the connector publishes every version of a document it sees within the history window, not just the latest version.
See xref:delivery-guarantees.adoc[] for details.
Requires Couchbase Server 7.2 or later.

* https://issues.couchbase.com/browse/KAFKAC-316[KAFKAC-316]:
Upgraded Couchbase DCP client from `0.43.0` to `0.44.0`.

* https://issues.couchbase.com/browse/KAFKAC-317[KAFKAC-317]:
Upgraded Couchbase Java SDK from `3.4.1` to `3.4.3`.


[[v4.1.10]]
== Version 4.1.10 (20 December 2022)

https://packages.couchbase.com/clients/kafka/4.1.10/couchbase-kafka-connect-couchbase-4.1.10.zip[Download]

Dependency updates and source connector improvements.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-303[KAFKAC-303]:
*Source* The connector now includes DCP snapshot boundaries in its source offsets.
This improves the reliability of resuming from saved offsets.

* https://issues.couchbase.com/browse/KAFKAC-302[KAFKAC-302]:
*Source* The connector now logs more diagnostic information about lifecycle milestones.

* https://issues.couchbase.com/browse/KAFKAC-301[KAFKAC-301]:
Upgraded Couchbase DCP client from `0.42.0` to `0.43.0`.

* https://issues.couchbase.com/browse/KAFKAC-305[KAFKAC-305]:
Upgraded Couchbase Java SDK from `3.3.4` to `3.4.1`.

=== Bug Fixes

* https://issues.couchbase.com/browse/JDCP-232[JDCP-232]:
Fixed a race condition that sometimes caused the connector to fail on startup with the message:
`java.lang.IllegalStateException: Tried to add duplicate channel`.


[[v4.1.9]]
== Version 4.1.9 (21 October 2022)

https://packages.couchbase.com/clients/kafka/4.1.9/couchbase-kafka-connect-couchbase-4.1.9.zip[Download]

You can now authenticate with Couchbase as an LDAP user, as long as secure connections are enabled.

=== Breaking Changes

* The Couchbase `dcp-client` library no longer includes a repackaged version of Jackson.
If you have written your own custom `Filter`, `SourceHandler`, or `SinkHandler` component that depends on the DCP client's repackaged Jackson, search for:
+
[source,java]
----
import com.couchbase.client.dcp.deps.
----
+
and replace with:
+
[source,java]
----
import com.couchbase.client.core.deps.
----
to use the version in the Couchbase `core-io` library instead.

=== Enhancements

* https://issues.couchbase.com/browse/JDCP-224[JDCP-224]:
Use SASL mechanism `PLAIN` when authenticating with Couchbase on a secure connection.
`PLAIN` is the fastest mechanism, and the only one that works with LDAP users.

* https://issues.couchbase.com/browse/JDCP-217[JDCP-217]:
Support Couchbase clusters that advertise only TLS ports.

* https://issues.couchbase.com/browse/KAFKAC-299[KAFKAC-299]:
Upgrade Couchbase DCP client from `0.41.0` to `0.42.0`.

[[v4.1.8]]
== Version 4.1.8 (20 September 2022)

https://packages.couchbase.com/clients/kafka/4.1.8/couchbase-kafka-connect-couchbase-4.1.8.zip[Download]

This version improves support for scopes & collections, adds an experimental `AnalyticsSinkHandler`, and adds a new feature that may reduce rollbacks by telling the Kafka Connect framework about the source offsets of ignored Couchbase events.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-295[KAFKAC-295]
*Source* The new `couchbase.collection.to.topic` config property lets you specify an arbitrary mapping from Couchbase scope & collection to Kafka topic.
This is useful when the `couchbase.topic` property is not sufficient because the desired topic name differs from the collection name.
Thanks to Shahrzad Haji Amin Shirazi.

* https://issues.couchbase.com/browse/KAFKAC-293[KAFKAC-293]
*Sink* `N1qlSinkHandler` now honors the configured destination scope & collection.
Thanks to Shahrzad Haji Amin Shirazi.

* https://issues.couchbase.com/browse/KAFKAC-294[KAFKAC-294]
*Sink* The new experimental `AnalyticsSinkHandler` sends documents directly to the Analytics service.
Thanks to Shahrzad Haji Amin Shirazi.

* https://issues.couchbase.com/browse/KAFKAC-296[KAFKAC-296]
*Source* In extremely low-traffic environments that ignore a majority of Couchbase events, the new `couchbase.black.hole.topic` config property may reduce the occurrence of rollback to zero.
If a topic is specified, the connector sends a tiny record to this topic for each ignored event, to inform Kafka Connect about the event's source offset.

* https://issues.couchbase.com/browse/KAFKAC-297[KAFKAC-297]:
Upgraded Couchbase Java SDK from 3.3.0 to 3.3.4.

* https://issues.couchbase.com/browse/KAFKAC-298[KAFKAC-298]:
Upgraded DCP client from 0.40.0 to 0.41.0

[[v4.1.7]]
== Version 4.1.7 (17 May 2022)

https://packages.couchbase.com/clients/kafka/4.1.7/couchbase-kafka-connect-couchbase-4.1.7.zip[Download]

This version makes it easier to connect to Capella.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-290[KAFKAC-290]
When connecting to Capella, it is no longer necessary to configure the Certificate Authority certificate.
All you need to do is enable TLS.

* https://issues.couchbase.com/browse/KAFKAC-288[KAFKAC-288]:
Upgraded Couchbase Java SDK from 3.2.5 to 3.3.0.

[[v4.1.6]]
== Version 4.1.6 (15 Feb 2022)

https://packages.couchbase.com/clients/kafka/4.1.6/couchbase-kafka-connect-couchbase-4.1.6.zip[Download]

Recommended for all users, this version fixes a memory leak when the connector stops.

=== Bug Fixes

* https://issues.couchbase.com/browse/KAFKAC-283[KAFKAC-283]:
The connector no longer leaks JMX MBeans on shutdown.
The leak was a regression in version 4.0.2.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-284[KAFKAC-284]
*Source* Added a new `couchbase.enable.dcp.trace` config option for enabling a DCP protocol trace to assist with diagnosing connector issues.
Also added `couchbase.dcp.trace.document.id.regex` to narrow the scope of the trace.

* https://issues.couchbase.com/browse/KAFKAC-286[KAFKAC-286]:
Upgraded Couchbase Java SDK from 3.2.4 to 3.2.5.

* https://issues.couchbase.com/browse/KAFKAC-287[KAFKAC-287]:
Upgraded Couchbase DCP Client from 0.39.0 to 0.40.0.

[[v4.1.5]]
== Version 4.1.5 (18 Jan 2022)

https://packages.couchbase.com/clients/kafka/4.1.5/couchbase-kafka-connect-couchbase-4.1.5.zip[Download]

This version upgrades the Couchbase clients and other dependencies.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-279[KAFKAC-279]:
Upgraded Couchbase DCP Client from 0.37.0 to 0.39.0:

** https://issues.couchbase.com/browse/JDCP-208[JDCP-208]
Improved the error message when the Couchbase user has insufficient permissions.

** https://issues.couchbase.com/browse/JDCP-210[JDCP-210]
Authentication no longer fails when credentials have non-ASCII characters and the system default encoding is not UTF-8.

* https://issues.couchbase.com/browse/KAFKAC-281[KAFKAC-281]:
Upgraded Couchbase Java SDK from 3.2.3 to https://docs.couchbase.com/java-sdk/current/project-docs/sdk-release-notes.html#version-3-2-4-9-december-2021[3.2.4].

* https://issues.couchbase.com/browse/KAFKAC-282[KAFKAC-282]:
Upgraded other dependencies to latest versions.

[[v4.1.4]]
== Version 4.1.4 (16 Nov 2021)

https://packages.couchbase.com/clients/kafka/4.1.4/couchbase-kafka-connect-couchbase-4.1.4.zip[Download]

This version adds a new configuration options for making the connector resilient to more kinds of transient failures.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-275[KAFKAC-275]:
*Sink* Added the `couchbase.retry.timeout` config property.
If non-zero, the connector retries write failures until the timeout expires.
This is better than simply extending the KV timeout; see xref:sink-configuration-options.adoc#couchbase.retry.timeout[the documentation] for details.

* https://issues.couchbase.com/browse/KAFKAC-276[KAFKAC-276]:
Upgraded Couchbase Java SDK from 3.2.0 to 3.2.3.

[[v4.1.3]]
== Version 4.1.3 (19 Oct 2021)

https://packages.couchbase.com/clients/kafka/4.1.3/couchbase-kafka-connect-couchbase-4.1.3.zip[Download]

This version reduces the default flow control buffer size to a more reasonable value and improves DCP diagnostics.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-271[KAFKAC-271]:
*Source* The default flow control buffer size is now 16 MB instead of 128 MB.
This makes it less likely the source connector will run out of memory under heavy load with the default heap size.
The documentation now describes how the https://docs.couchbase.com/kafka-connector/current/source-configuration-options.html#couchbase.flow.control.buffer[couchbase.flow.control.buffer] config property affects the Kafka Connect worker's memory requirements.

* https://issues.couchbase.com/browse/KAFKAC-272[KAFKAC-272]:
*Source* Upgraded DCP client from 0.36.0 to 0.37.0.
This upgrade adds a workaround for https://issues.couchbase.com/browse/MB-48655[MB-48655] so all versions of Couchbase now correctly log DCP diagnostic messages from the source connector.

[[v4.1.2]]
== Version 4.1.2 (24 Sep 2021)

https://packages.couchbase.com/clients/kafka/4.1.2/couchbase-kafka-connect-couchbase-4.1.2.zip[Download]

This release upgrades the jsoup library to address https://github.com/jhy/jsoup/security/advisories/GHSA-m72m-mhq2-9p6c[CVE-2021-37714].
That vulnerability does not affect the Kafka connector, since we don't parse untrusted XML or HTML.
You can skip this version unless your goal is to pacify a vulnerability scanner.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-269[KAFKAC-269]:
Upgraded the jsoup library from 1.13.1 to 1.14.2

[[v4.1.1]]
== Version 4.1.1 (19 Aug 2021)

https://packages.couchbase.com/clients/kafka/4.1.1/couchbase-kafka-connect-couchbase-4.1.1.zip[Download]

This release makes the Source connector compatible with Couchbase Server 7.0.2.

If you are currently using an earlier 4.x version of the connector, please upgrade to 4.1.1 or later before upgrading Couchbase Server beyond 7.0.1.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-266[KAFKAC-266]:
*Source* Upgraded DCP client from 0.35.0 to 0.36.0 for compatibility with Couchbase Server 7.0.2.

[[v4.1.0]]
== Version 4.1.0 (22 July 2021)

https://packages.couchbase.com/clients/kafka/4.1.0/couchbase-kafka-connect-couchbase-4.1.0.zip[Download]

This release stabilizes the configuration options for working with Couchbase 7 Scopes and Collections.
All previously "uncommitted" options are promoted to "committed" status.

There's also a new `SinkHandler` extension point, and bug fixes for the Subdocument and N1QL modes of operation.

=== Breaking Changes

* Apache Kafka 2.4.0 is now the minimum required version.
For Confluent Platform users, this corresponds to Confluent version 5.4.0.

=== Enhancements

* The config options for working with Couchbase 7 Scopes and Collections are now part of the "committed" API.

* All other "uncommitted" config options are promoted to "committed" status as well.

* https://issues.couchbase.com/browse/KAFKAC-257[KAFKAC-257]:
*Sink* The connector's behavior is now completely customizable by implementing the `SinkHandler` interface.
The new xref:sink-configuration-options.adoc#couchbase.sink.handler[couchbase.sink.handler] config option specifies the class to use.
See the https://github.com/couchbase/kafka-connect-couchbase/tree/master/examples/custom-extensions[custom extensions example code] to see how to implement your own handler.

NOTE: The xref:sink-configuration-options.adoc#couchbase.document.mode[couchbase.document.mode] config option is now **DEPRECATED**.
Instead, please use xref:sink-configuration-options.adoc#couchbase.sink.handler[couchbase.sink.handler] to specify one of the built-in handler classes.

* https://issues.couchbase.com/browse/KAFKAC-263[KAFKAC-263]:
*Source* Upgraded DCP client from 0.34.0 to 0.35.0.

* https://issues.couchbase.com/browse/KAFKAC-258[KAFKAC-258]:
*Sink* Upgraded Couchbase Java SDK from 3.1.3 to 3.2.0.

=== Bug Fixes

* https://issues.couchbase.com/browse/KAFKAC-261[KAFKAC-261]:
*Sink* A connector configured to use SUBDOCUMENT mode with an operation of `ARRAY_PREPEND` or `ARRAY_PREPEND` could mistakenly ignore updates if Kafka records targeting the same document arrive in rapid succession.
This is now fixed.

* https://issues.couchbase.com/browse/KAFKAC-262[KAFKAC-262]:
*Sink* A connector configured to use N1QL mode could mistakenly ignore updates if Kafka records targeting the same document(s) arrive in rapid succession.
This is now fixed.

[[v4.0.6]]
== Version 4.0.6 (20 April 2021)

https://packages.couchbase.com/clients/kafka/4.0.6/couchbase-kafka-connect-couchbase-4.0.6.zip[Download]

This release adds new Sink configuration options, and addresses a long-standing issue that caused the Source connector to fail when a rollback occurred in Couchbase.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-250[KAFKAC-250]:
*Sink* You can now xref:sink-configuration-options.adoc#couchbase.env[configure Couchbase Java SDK Settings] in the connector config file.
This includes KV timeout durations, Response Time Observability settings, and lots more.

* https://issues.couchbase.com/browse/KAFKAC-251[KAFKAC-251]:
*Source* Upgraded DCP client from 0.33.0 to 0.34.0.

=== Bug Fixes

* https://issues.couchbase.com/browse/KAFKAC-211[KAFKAC-211]:
*Source* A rollback in Couchbase no longer causes the connector to fail.

[[v4.0.5]]
== Version 4.0.5 (16 March 2021)

https://packages.couchbase.com/clients/kafka/4.0.5/couchbase-kafka-connect-couchbase-4.0.5.zip[Download]

This release improves diagnostic logging and simplifies Couchbase Capella configuration.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-234[KAFKAC-234]:
The Couchbase root CA certificate can now be read directly from a PEM file; it's no longer necessary to add it to a Java keystore first.
The new `couchbase.trust.certificate.path` config property points to the PEM file.

* https://issues.couchbase.com/browse/KAFKAC-242[KAFKAC-242]:
*Source* When the new `couchbase.log.document.lifecycle` config property is set to true, the connector writes detailed log entries as each document flows through the connector.

* https://issues.couchbase.com/browse/KAFKAC-245[KAFKAC-245]:
*Sink* Upgraded Couchbase client from 3.1.2 to https://docs.couchbase.com/java-sdk/3.1/project-docs/sdk-release-notes.html#version-3-1-3-2-march-2021[3.1.3].

* https://issues.couchbase.com/browse/KAFKAC-246[KAFKAC-246]:
*Source* Upgraded DCP client from 0.32.0 to 0.33.0.
OBSERVE_SEQNO events are now logged at TRACE level instead of DEBUG.

[[v4.0.4]]
== Version 4.0.4 (17 February 2021)

https://packages.couchbase.com/clients/kafka/4.0.4/couchbase-kafka-connect-couchbase-4.0.4.zip[Download]

This release adds uncommitted support for client certificate authentication (mTLS), adds hostname verification for secure DCP connections, and improves the stability of the connector.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-241[KAFKAC-241]:
When secure connections are enabled, it is now possible to authenticate with Couchbase using an X.509 certificate instead of a username & password.
See https://docs.couchbase.com/kafka-connector/4.0/source-configuration-options.html#couchbase.client.certificate.path[couchbase.client.certificate.path]
and https://docs.couchbase.com/kafka-connector/4.0/source-configuration-options.html#couchbase.client.certificate.password[couchbase.client.certificate.password]
for details. (This feature is added as "uncommitted", meaning it may change without notice.)

* https://issues.couchbase.com/browse/KAFKAC-238[KAFKAC-238]:
*Sink* Upgraded Couchbase client from 3.0.9 to 3.1.2.

* https://issues.couchbase.com/browse/KAFKAC-239[KAFKAC-239]:
*Source* Upgraded DCP client from 0.31.0 to 0.32.0.
Previously, TLS hostname verification was done only for the Couchbase Java client connection; now the DCP client connection is verified as well.
If for some reason you need to disable TLS hostname verification, this is now possible by setting the
https://docs.couchbase.com/kafka-connector/4.0/source-configuration-options.html#couchbase.enable.hostname.verification[couchbase.enable.hostname.verification] config property to `false`.

=== Bug Fixes

** https://issues.couchbase.com/browse/JDCP-183[JDCP-183]:
If an invalid stream offset is detected, the connector will now fail fast instead of potentially corrupting the saved checkpoint.

** https://issues.couchbase.com/browse/JDCP-184[JDCP-184]:
Resolved an issue that could cause a flow control deadlock when streaming from a subset of a bucket's collections or scopes.

[[v4.0.3]]
== Version 4.0.3

Not released.

[[v4.0.2]]
== Version 4.0.2 (17 November 2020)

https://packages.couchbase.com/clients/kafka/4.0.2/couchbase-kafka-connect-couchbase-4.0.2.zip[Download]

In this release, the connector publishes metrics via JMX to facilitate monitoring.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-152[KAFKAC-152]:
*Documentation* - Added a "Monitoring" page which refers users to the Kafka Connect framework documentation for monitoring connectors via JMX.

* https://issues.couchbase.com/browse/KAFKAC-232[KAFKAC-232]:
*Source* - Metrics specific to the Couchbase source connector are now exposed via JMX under the `kafka.connect.couchbase` domain.

* https://issues.couchbase.com/browse/KAFKAC-110[KAFKAC-110]:
*Source* - Added a gauge that reports the Couchbase connection status.

* https://issues.couchbase.com/browse/KAFKAC-231[KAFKAC-231]:
*Source* - Upgrade DCP client from 0.30.0 to 0.31.0

[[v4.0.1]]
== Version 4.0.1 (20 October 2020)

https://packages.couchbase.com/clients/kafka/4.0.1/couchbase-kafka-connect-couchbase-4.0.1.zip[Download]

This release improves compatibility with Couchbase Capella, and exposes extended attributes (XATTRS) to custom components.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-227[KAFKAC-227]:
*Source* - Added config property `couchbase.xattrs` (boolean, defaults to false).
If set to true, a custom `Filter` or `SourceHandler` may inspect a document's extended attributes by calling `DocumentEvent.xattrs()`.

* https://issues.couchbase.com/browse/KAFKAC-226[KAFKAC-226]:
Renamed the ZIP archive from `couchbaseinc-kafka-connect-couchbase` to `couchbase-kafka-connect-couchbase` (removed the "inc" from "couchbaseinc").
This made it easier to publish the connector on https://www.confluent.io/hub/couchbase/kafka-connect-couchbase[Confluent Hub].

* https://issues.couchbase.com/browse/KAFKAC-228[KAFKAC-228]:
Upgraded the Couchbase Java SDK from 3.0.6 to 3.0.9.
Bootstrap performance is improved when specifying custom ports, and the connector no longer logs spurious warnings about being unable to fetch collections manifests.

* https://issues.couchbase.com/browse/KAFKAC-229[KAFKAC-229]:
Upgraded the DCP client from 0.29.0 to 0.30.0, adding support for XATTRs.

=== Bug Fixes

* https://issues.couchbase.com/browse/KAFKAC-225[KAFKAC-225]:
Fixed a regression in version 4.0.0 that broke alternate address resolution.
The connector now handles DNS SRV and alternate addresses correctly, and can connect to Couchbase Capella or other network environments that use alternate addresses.

[[v4.0.0]]
== Version 4.0.0 (18 August 2020)

https://packages.couchbase.com/clients/kafka/4.0.0/couchbaseinc-kafka-connect-couchbase-4.0.0.zip[Download]

Version 4.0 is a major update that changes how you configure and extend the connector.
If you are upgrading from a previous version of the connector, be sure to read the xref:migration.adoc[Migration Guide] which will help with the upgrade process.

The leap to 4.0 brings many new features, most notably:

* Enhanced durability options (requires Couchbase 6.5)
* Better workload distribution
* More flexible API for extensions
* Option to omit document contents
* Support for Couchbase collections and scopes (planned for Couchbase 7.0)

The notes below describe these features, and more.

WARNING: The new configuration properties related to Couchbase scopes and collections are "uncommitted" and may change without notice in a patch release.

=== Enhancements
[abstract]
Complete list of changes since version 3.4.8

* https://issues.couchbase.com/browse/KAFKAC-192[KAFKAC-192]:
Renamed the connector config properties to follow the standard Kafka naming convention ("lowercase.with.dots.between.words").
See the xref:migration.adoc[Migration Guide] for a comprehensive list of changes, and a shell script that can help upgrade your 3.x config files to use the new property names.

* https://issues.couchbase.com/browse/KAFKAC-157[KAFKAC-157]:
The connector is now packaged as a Confluent Hub component.
Confluent Platform users can easily install the connector using the `confluent-hub install` command.
The xref:quickstart.adoc[Quickstart Guide] has been updated to show how Apache Kafka users can install the connector.

* https://issues.couchbase.com/browse/KAFKAC-167[KAFKAC-167]:
You can now specify custom ports in the list of Couchbase seed nodes.
If you specify a port, it must be the port of the Key/Value service (which defaults to 11210 for unencrypted connections).

* https://issues.couchbase.com/browse/KAFKAC-207[KAFKAC-207]:
*Sink* - You can now specify an "enhanced durability" requirement with the new `couchbase.durability` config property.
Enhanced durability requires Couchbase Server 6.5 or later.

* https://issues.couchbase.com/browse/KAFKAC-197[KAFKAC-197]:
*Sink* - Added config property `couchbase.topic.to.collection` which maps Kafka topics to Couchbase collections.
Added config property `couchbase.default.collection` which is used when a message's topic is not present in the map.

* https://issues.couchbase.com/browse/KAFKAC-209[KAFKAC-209]:
*Source* - The connector now evenly distributes the workload among all tasks, instead of trying to minimize the total number of Couchbase connections.

* https://issues.couchbase.com/browse/KAFKAC-177[KAFKAC-177]:
*Source* - The example config files now use `RawJsonSourceHandler` and publish Kafka messages whose contents are the same as the Couchbase documents.

* https://issues.couchbase.com/browse/KAFKAC-212[KAFKAC-212]:
*Source* - If you don't care about the content of the Couchbase document, you can set the new `couchbase.no.value` config property to `true`, and the connector will omit the document content from Kafka messages.

* https://issues.couchbase.com/browse/KAFKAC-194[KAFKAC-194]:
*Source* - A custom `SourceHandler` can now set headers on the Kafka record.

* https://issues.couchbase.com/browse/KAFKAC-223[KAFKAC-223]:
*Source* - The connector is now more responsive to "pause" requests.

* https://issues.couchbase.com/browse/KAFKAC-220[KAFKAC-220]:
*Source* - Custom `Filter` and `SourceHandler` components can now access connector configuration properties.
These interfaces now have an `init(Map<String, String>)` method.
The connector config is passed to this method when the component is created.

* https://issues.couchbase.com/browse/KAFKAC-222[KAFKAC-222]:
The `custom-extensions` example project now includes a `CustomFilter` class that demonstrates how to read properties from the connector config.
This example filter accepts or rejects documents based on a field of the document.
The target field and the list of acceptable values are both configurable.

* https://issues.couchbase.com/browse/KAFKAC-196[KAFKAC-196]:
*Source* - Added `couchbase.scope` and `couchbase.collection` config properties that let you stream from a specific scope or set of collections.

* https://issues.couchbase.com/browse/KAFKAC-195[KAFKAC-195]:
*Source* - Modified the `couchbase.topic` config property to be a format string that supports `${bucket}`, `${scope}`, and `${collection}` placeholders.
This makes it easy to publish to different Kafka topics depending on the Couchbase document's parent collection.
The default value is `${bucket}.${scope}.${collection}`.

* https://issues.couchbase.com/browse/KAFKAC-171[KAFKAC-171]:
The `couchbase.password` config property (previously called `connection.password`) no longer defaults to an empty string.

* https://issues.couchbase.com/browse/KAFKAC-175[KAFKAC-175]:
APIs deprecated in version 3.x have been removed.

* Upgraded Kafka Connect API from 1.0.2 to 2.5.0.

* Upgraded Couchbase client from 2.7.13 to 3.0.6.

* Upgraded DCP client from 0.26.0 to 0.29.0.

=== Bug Fixes

[abstract]
Complete list of changes since version 3.4.8

* https://issues.couchbase.com/browse/KAFKAC-169[KAFKAC-169]:
*Sink* - If two Kafka messages with the same key arrive in rapid succession, it's no longer theoretically possible for them to be written to Couchbase in the wrong order.

=== Changes since 4.0.0-dp.3

* https://issues.couchbase.com/browse/KAFKAC-220[KAFKAC-220]:
*Source* - Custom `Filter` and `SourceHandler` components can now access connector configuration properties.
These interfaces now have an `init(Map<String, String>)` method.
The connector config is passed to this method when the component is created.

* https://issues.couchbase.com/browse/KAFKAC-222[KAFKAC-222]:
The `custom-extensions` example project now includes a `CustomFilter` class that demonstrates how to read properties from the connector config.
This example filter accepts or rejects documents based on a field of the document.
The target field and the list of acceptable values are both configurable.

[[v4.0.0-dp.3]]
== Version 4.0.0-dp.3 (21 July 2020)

https://packages.couchbase.com/clients/kafka/4.0.0-dp.3/couchbaseinc-kafka-connect-couchbase-4.0.0-dp.3.zip[Download]

In this developer preview, both the Sink and Source connector now support Couchbase collections.
This preview also brings a handful of fixes and new features, including support for enhanced durability, and optionally omitting document contents.

NOTE: The new features in this pre-release version should be considered "volatile" and may change before the 4.0.0 GA release.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-197[KAFKAC-197]:
*Sink* - Added config property `couchbase.topic.to.collection` which maps Kafka topics to Couchbase collections.
Added config property `couchbase.default.collection` which is used when a message's topic is not present in the map.

* https://issues.couchbase.com/browse/KAFKAC-207[KAFKAC-207]:
*Sink* - You can now specify an "enhanced durability" requirement with the new `couchbase.durability` config property.
Enhanced durability requires Couchbase Server 6.5 or later.

* https://issues.couchbase.com/browse/KAFKAC-206[KAFKAC-206]:
*Source* - Config property `couchbase.connector.name.in.offsets` now defaults to false again.
This property doesn't do anything useful, and should only be set to `true` if you previously had `compat.connector_name_in_offsets` set to `true`.

* https://issues.couchbase.com/browse/KAFKAC-177[KAFKAC-177]:
*Source* - The example config files now use `RawJsonSourceHandler` and publish Kafka messages whose contents are the same as the Couchbase documents.

* https://issues.couchbase.com/browse/KAFKAC-209[KAFKAC-209]:
*Source* - The connector now evenly distributes the workload among all tasks, instead of trying to minimize the total number of Couchbase connections.

* https://issues.couchbase.com/browse/KAFKAC-212[KAFKAC-212]:
*Source* - If you don't care about the content of the Couchbase document, you can set the new `couchbase.no.value` config property to `true`, and the connector will omit the document content from Kafka messages.

* https://issues.couchbase.com/browse/KAFKAC-205[KAFKAC-205]:
Removed the unused `couchbase.force.ipv4` config property.

=== Bug Fixes

* https://issues.couchbase.com/browse/KAFKAC-169[KAFKAC-169]:
*Sink* - If two Kafka messages with the same key arrive in rapid succession, it's no longer theoretically possible for them to be written to Couchbase in the wrong order.

* https://issues.couchbase.com/browse/KAFKAC-214[KAFKAC-214]:
*Sink* - The Couchbase Java SDK has been updated from 3.0.5 to 3.0.6.
As a result, setting `couchbase.document.expiration` to longer than 30 days now works correctly instead of causing immediate expiration.
(This was a regression in 4.0.0-dp.1.)

* https://issues.couchbase.com/browse/KAFKAC-203[KAFKAC-203]:
*Source* - The 3.x -> 4.0 migration script now properly converts the old `couchbase.flow_control_buffer` property to the new name: `couchbase.flow.control.buffer.size`.

* https://issues.couchbase.com/browse/KAFKAC-204[KAFKAC-204]:
*Source* - Fixed the invalid value for `couchbase.bootstrap.timeout` in the `quickstart-couchbase-source.json` example config file.

[[v4.0.0-dp.1]]
== Version 4.0.0-dp.1 (17 June 2020)

https://packages.couchbase.com/clients/kafka/4.0.0-dp.1/couchbaseinc-kafka-connect-couchbase-4.0.0-dp.1.zip[Download]

This developer preview version offers a sneak peek at some features coming in version 4.0.0 of the Couchbase Kafka connector, including support for Couchbase Collections and Scopes.

Version 4.0 is a major update that changes how you configure and extend the connector.
If you are upgrading from a previous version of the connector, be sure to read the xref:migration.adoc[Migration Guide] which will help you with the upgrade process.

NOTE: The new features in this pre-release version should be considered "volatile" and may change before the 4.0.0 GA release.

=== Enhancements

* https://issues.couchbase.com/browse/KAFKAC-182[KAFKAC-182]:
Upgraded Kafka Connect API from 1.0.2 to 2.5.0.

* https://issues.couchbase.com/browse/KAFKAC-188[KAFKAC-188]:
Upgraded Couchbase client from 2.7.13 to 3.0.5.

* https://issues.couchbase.com/browse/KAFKAC-189[KAFKAC-189]:
Upgraded DCP client from 0.26.0 to 0.28.0.

* https://issues.couchbase.com/browse/KAFKAC-192[KAFKAC-192]:
Renamed the connector config properties to follow the standard Kafka naming convention ("lowercase.with.dots.between.words").
See the xref:migration.adoc[Migration Guide] for a comprehensive list of changes, and a shell script that can help upgrade your 3.x config files to use the new property names.

* https://issues.couchbase.com/browse/KAFKAC-196[KAFKAC-196]:
Source: Added `couchbase.scope` and `couchbase.collection` config properties that let you stream from a specific scope or set of collections.

* https://issues.couchbase.com/browse/KAFKAC-195[KAFKAC-195]:
Source: Modified the `couchbase.topic` config property to be a format string that supports `${bucket}`, `${scope}`, and `${collection}` placeholders.
This makes it easy to publish to different Kafka topics depending on the Couchbase document's parent collection.
The default value is `${bucket}.${scope}.${collection}`.

* https://issues.couchbase.com/browse/KAFKAC-194[KAFKAC-194]:
Source: A custom `SourceHandler` can now set headers on the Kafka record.

* https://issues.couchbase.com/browse/KAFKAC-157[KAFKAC-157]:
The connector is now packaged as a Confluent Hub component.
Confluent Platform users can easily install the connector using the `confluent-hub install` command.
The xref:quickstart.adoc[Quickstart Guide] has been updated to show how Apache Kafka users can install the connector.

* https://issues.couchbase.com/browse/KAFKAC-167[KAFKAC-167]:
You can now specify custom ports in the list of Couchbase seed nodes.
If you specify a port, it must be the port of the Key/Value service (which defaults to 11210 for unencrypted connections).

* https://issues.couchbase.com/browse/KAFKAC-171[KAFKAC-171]:
The `couchbase.password` config property (previously called `connection.password`) no longer defaults to an empty string.

* https://issues.couchbase.com/browse/KAFKAC-173[KAFKAC-173]:
The `couchbase.connector.name.in.offsets` config property (previously called `compat.connector_name_in_offsets`) now defaults to `true`.

* https://issues.couchbase.com/browse/KAFKAC-175[KAFKAC-175]:
APIs deprecated in version 3.x have been removed.



== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].

*Parent topic:* xref:index.adoc[Kafka Connector]

*Previous topic:* xref:streams-sample.adoc[Couchbase Sample with Kafka Streams]
