name: Maven Deploy Snapshot

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.adoc'
      - '.gitignore'
      - '.editorconfig'
      - 'examples/**'
      - '.github/workflows/**'
      - '!.github/workflows/deploy-snapshot.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

          server-id: 'central'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

          cache: 'maven'

      - name: Printing maven version
        run: ./mvnw --version

      - name: Build and deploy to Maven Central
        run: ./mvnw -e -X deploy --batch-mode -Dgpg.signer=bc -Psnapshot
        env:
          MAVEN_USERNAME: ${{ vars.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.SDK_ROBOT_GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ''

      - name: Remove artifacts from Maven repo so they're not cached
        run: rm -rfv ~/.m2/repository/com/couchbase/client/
